server:
  port: ${RECOVERY_ERROR_TOPIC_SERVER:8080}

reactor:
  bufferSize:
    small: ${REACTOR_BUFFER_SIZE:256}

spring:
  application:
    name: idpay-recovery-error-topic
  jmx.enabled: true
  kafka:
    client-id: ${KAFKA_ERROR_MESSAGE_CLIENT_ID:idpay-errors-recovery}
    consumer:
      bootstrap-servers: ${KAFKA_ERROR_MESSAGE_SERVERS:${KAFKA_SERVERS:localhost:9092}}
      group-id: ${KAFKA_ERROR_MESSAGE_GROUP_ID:idpay-errors-recovery}
      auto-offset-reset: ${KAFKA_ERROR_MESSAGE_OFFSET_RESET:earliest}
      enable-auto-commit: ${KAFKA_ERROR_MESSAGE_ENABLE_AUTO_COMMIT:true}
      heartbeat-interval: ${KAFKA_ERROR_MESSAGE_HEARTBEAT_INTERVAL:20000}
      security.protocol: ${KAFKA_ERROR_MESSAGE_SECURITY_PROTOCOL:${KAFKA_SECURITY_PROTOCOL:SASL_SSL}}
      properties:
        sasl.mechanism: ${KAFKA_ERROR_MESSAGE_SASL_MECHANISM:${KAFKA_SASL_MECHANISM:PLAIN}}
        sasl.jaas.config: ${KAFKA_ERROR_MESSAGE_SASL_JAAS_CONFIG:${KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${KAFKA_ERROR_MESSAGE_CONNECTION_STRING:}";}}
        max.poll:
          records: ${KAFKA_ERROR_MESSAGE_MAX_POLL_SIZE:500}
          interval.ms: ${KAFKA_ERROR_MESSAGE_POLL_INTERVAL:60000}
        request.timeout.ms: ${KAFKA_ERROR_MESSAGE_REQUEST_TIMEOUT:60000}
        session.timeout.ms: ${KAFKA_ERROR_MESSAGE_SESSION_TIMEOUT:30000}
        connections.max.idle.ms: ${KAFKA_ERROR_MESSAGE_CONNECTION_MAX_IDLE_TIME:180000}
        metadata.max.age.ms: ${KAFKA_ERROR_MESSAGE_METADATA_MAX_AGE_INTERVAL:180000}
    listener:
      concurrency: ${KAFKA_ERROR_MESSAGE_CONCURRENCY:2}
      ack-mode: ${KAFKA_ERROR_MESSAGE_ACK_MODE:BATCH}
      ack-count: ${KAFKA_ERROR_MESSAGE_ACK_COUNT:100}
      ack-time: ${KAFKA_ERROR_MESSAGE_ACK_TIME:30000}
    producer:
      retries: ${KAFKA_PRODUCER_DEFAULT_RETRIES:3}
      security.protocol: ${KAFKA_PRODUCER_DEFAULT_SECURITY_PROTOCOL:${KAFKA_SECURITY_PROTOCOL:SASL_SSL}}
      properties:
        sasl.mechanism: ${KAFKA_PRODUCER_DEFAULT_SASL_MECHANISM:${KAFKA_SASL_MECHANISM:PLAIN}}
        sasl.jaas.config: ${KAFKA_PRODUCER_DEFAULT_SASL_JAAS_CONFIG:${KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${KAFKA_ERROR_MESSAGE_CONNECTION_STRING:}";}}
        session.timeout.ms: ${KAFKA_PRODUCER_DEFAULT_SESSION_TIMEOUT:30000}
        connections.max.idle.ms: ${KAFKA_PRODUCER_DEFAULT_CONNECTION_MAX_IDLE_TIME:180000}
        retry.backoff.ms: ${KAFKA_PRODUCER_DEFAULT_KAFKA_RETRY_MS:${KAFKA_RETRY_MS:10000}}
        linger.ms: ${KAFKA_PRODUCER_DEFAULT_LINGER_MS:${KAFKA_LINGER_MS:2}}
        batch.size: ${KAFKA_PRODUCER_DEFAULT_BATCH_SIZE:${KAFKA_BATCH_SIZE:16384}}
  jms:
    servicebus:
      connection-string: ${SERVICEBUS_IDPAY_SB_CONNECTION_STRING:Endpoint=sb://ServiceBusEndpoint;SharedAccessKeyName=sharedAccessKeyName;SharedAccessKey=sharedAccessKey}
      # Specify the pricing tier of your service bus. Supported values are premium, standard, and basic. Premium uses Java Message Service (JMS) 2.0, while standard and basic use JMS 1.0 to interact with Azure Service Bus.
      pricing-tier: ${SERVICEBUS_IDPAY_SB_PRICING_TIER:standard}
      topic-client-id: ${SERVICE_BUS_ERROR_MESSAGE_CLIENT_ID:idpay-errors-recovery}

errorListener:
  topic: ${KAFKA_ERROR_MESSAGE_TOPIC:idpay-errors}
  idleInterval:
    minSeconds: ${ERROR_LISTENER_PAUSE_SECONDS:600}
    scheduleCheck: ${SCHEDULE_ERROR_LISTENER_RESUME:* */1 * * * ?}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    it.gov.pagopa: ${LOG_LEVEL_PAGOPA:INFO}
    it.gov.pagopa.idpay: ${LOG_LEVEL_IDPAY:INFO}
    it.gov.pagopa.idpay.error_revoery: ${LOG_LEVEL_ERROR_RECOVERY:INFO}
    org.springframework.integration: ${LOG_LEVEL_SPRING_INTEGRATION:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
    org.springframework.ws: ${LOG_LEVEL_SPRING_WS:INFO}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:INFO}
    org.springframework.hateoas: ${LOG_LEVEL_SPRING_HATEOAS:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    org.springframework.kafka: ${LOG_LEVEL_SPRING_KAFKA:INFO}
    org.springframework.batch: ${LOG_LEVEL_SPRING_BATCH:INFO}
    io.swagger: ${LOG_LEVEL_IO_SWAGGER:WARN}

app:
  threads:
    # the size of the thread pool to handle @Scheduled tasks
    schedule-max-number: ${THREADS_SCHEDULE_MAX_NUMBER:1}
  retry.max-retry: ${ERROR_MESSAGE_MAX_RETRY:10}
