microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: false

  serviceAccount:
    create: false

  podAnnotations: { }

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "idpay-recovery-error-topic"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"

  envConfigMapExternals:
    idpay-common:
      TZ: TZ
    idpay-eventhub-00:
      KAFKA_EVENTHUB_00_BROKER: kafka_broker
      KAFKA_EVENTHUB_00_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_EVENTHUB_00_SECURITY_PROTOCOL: kafka_security_protocol
    idpay-eventhub-01:
      KAFKA_EVENTHUB_01_BROKER: kafka_broker
      KAFKA_EVENTHUB_01_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_EVENTHUB_01_SECURITY_PROTOCOL: kafka_security_protocol
    rtd-eventhub:
      KAFKA_RTD_BROKER: kafka_broker_rtd

  envSecret:
    #    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    KAFKA_ERRORS_SASL_JAAS_CONFIG: evh-idpay-errors-idpay-errors-consumer-jaas-config-idpay-01
    SERVICEBUS_ONBOARDING_CONNECTION_STRING: idpay-onboarding-request-processor-sas-key

    # if we cannot use high level keys, we should configure each of them
    KAFKA_RTD_TRX_SASL_JAAS_CONFIG: evh-rtd-trx-rtd-trx-producer-jaas-config
    KAFKA_TRANSACTION_SASL_JAAS_CONFIG: evh-idpay-transaction-idpay-transaction-producer-jaas-config-idpay-01
    KAFKA_RULE_UPDATE_SASL_JAAS_CONFIG: evh-idpay-rule-update-idpay-rule-update-producer-jaas-config-idpay-01
    KAFKA_TRANSACTION_USER_ID_SPLITTER_SASL_JAAS_CONFIG: evh-idpay-transaction-user-id-splitter-idpay-transaction-user-id-splitter-producer-jaas-config-idpay-01
    KAFKA_HPAN_UPDATE_SASL_JAAS_CONFIG: evh-idpay-hpan-update-idpay-hpan-update-producer-jaas-config-idpay-01
    KAFKA_ONBOARDING_OUTCOME_SASL_JAAS_CONFIG: evh-idpay-onboarding-outcome-idpay-onboarding-outcome-producer-jaas-config-idpay-00